src/api/urls.py
from django.urls import path
from api.views import *
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

app_name = "api"

urlpatterns = [
    path('register/', RegisterApiView.as_view(), name='users_register'),
    path('token/', TokenObtainPairView.as_view(), name='token-obtain-pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token-refresh'),
    path('category/', CategoryListCreateAPIView.as_view(), name='category-list'),
    path('category/<int:pk>/', CategoryRetrieveUpdateAPIView.as_view(), name='category-retrieve-update-destroy'),

    path('product/', ProductListCreateView.as_view(), name='product_list'),
    path('product/<int:pk>/', ProductRetrieveUpdateAPIView.as_view(), name='product_retrieve_update_destroy'),
    path("blog/", BlogListCreateView.as_view(), name='blog_list'),
    path("blog/<int:pk>/", BlogRetrieveUpdateAPIView.as_view(), name='blog_retrieve_update_destroy'),
    path('media/<int:pk>/', MediaRetrieveUpdateAPIView.as_view(), name='media_retrieve_update_destroy'),
    path('display/<int:pk>/', DisplayRetrieveUpdateAPIView.as_view(), name='display_retrieve_update_destroy'),
    path('wireless/<int:pk>/', WirelessRetrieveUpdateAPIView.as_view(), name='wireless_retrieve_update_destroy'),
    path('campaign/<int:pk>/', CampaignRetrieveUpdateAPIView.as_view(), name='campaign_retrieve_update_destroy'),
    path('brand/<int:pk>/', BrandRetrieveUpdateAPIView.as_view(), name='brand_retrieve_update_destroy'),
    path('screen/<int:pk>/', ScreenRetrieveUpdateAPIView.as_view(), name='screen_retrieve_update_destroy'),
    path('cart/', CartListCreateAPIView.as_view(), name='cart_list_create'),
    path('cart/<int:pk>', CartRetrieveUpdateAPIView.as_view(), name='cart_retrieve_update_destroy'),
    path('cart-item/', CartItemListCreateAPIView.as_view(), name='cart_item_list_create'),
    path('cart-item/<int:pk>', CartItemRetrieveUpdateAPIView.as_view(), name='cart_retrieve_update_destroy'),
    path('order/', OrderListCreateAPIView.as_view(), name='order_list_create'),
    path('order/<int:pk>', OrderRetrieveUpdateAPIView.as_view(), name='order_retrieve_update_destroy'),
    path('order-item/', OrderItemListCreateAPIView.as_view(), name='order_item_list_create'),
    path('order-item/<int:pk>', OrderItemRetrieveUpdateAPIView.as_view(), name='order_retrieve_update_destroy'),
    path('wishlist/', WishlistListCreateAPIView.as_view(), name='wishlist_list_create'),
    path('wishlist/<int:pk>', WishlistRetrieveUpdateDestroyAPIView.as_view(), name='wishlist_retrieve_update_destroy'),
]

src/unistore/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

from core.views import search

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('blog/', include('blog.urls')),
    path('products/', include('product.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
   
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
  
    path('search/', search, name='search'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]
urlpatterns = [
    *i18n_patterns(*urlpatterns, prefix_default_language=False),
]

src/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from . import views

app_name = 'users'

urlpatterns = [
    path('wishlist/', views.wishlist, name='wishlist'),
    path('checkout/', views.checkout, name='checkout'),
    path('order-success', views.order_success, name='order-success'),
    path('user-login/', views.LoginView.as_view(), name='user-login'),
    path('register/', views.register, name='register'),
    path('login-user/', views.login_user, name='login'),
    path('auth-callback/', views.auth_callback, name='auth-callback'),
    path('logout/', views.logout, name='logout'),
    path('password-change/', 
        views.PasswordsChangeView.as_view(
            template_name='users/password/change-password.html'), 
        name='password-change'),

    path('password-reset/', views.custom_password_reset, name='password_reset'),

    path('password-reset/done/', 
        auth_views.PasswordResetDoneView.as_view(
            template_name='users/password/password_reset_done.html'), 
        name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(
            template_name='users/password/password_reset_confirm.html',
            success_url = reverse_lazy('users:user-login')), 
        name='password_reset_confirm'),

    path('activate/<uidb64>/<token>', views.activate, name='activate'),


]

src/users/views.py
import ast
from typing import Optional

from django.shortcuts import redirect, render
from django.urls import reverse_lazy, reverse
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.contrib.auth.views import PasswordChangeView, LoginView
from django.core.mail import BadHeaderError
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_str
from django.contrib.auth.forms import PasswordChangeForm, PasswordResetForm
from django.db.models.query_utils import Q
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, get_user_model, authenticate
from django.conf import settings
from urllib.parse import urlencode, quote_plus
from authlib.integrations.django_client import OAuth

from users.forms import CheckoutOrder, RegisterForm, LoginForm
from users.token import account_activation_token
from tasks.tasks import activation_mail, reset_password_mail
from users.services.user import (
    create_cart_after_user_registered, 
    get_order_details, get_user_cart, 
    create_user_if_not_exist)
from product.models import Product
from users.models import Order, Cart, OrderItem

UserModel = get_user_model()

class LoginView(LoginView):
    form_class = LoginForm
    template_name = 'users/login.html'

    def form_invalid(self, form) -> HttpResponse:
        print('here', form.errors)
        return super().form_invalid(form)

def custom_password_reset(request):
	if request.method == "POST":
		password_reset_form = PasswordResetForm(request.POST)
		if password_reset_form.is_valid():
			data = password_reset_form.cleaned_data['email']
			user = UserModel.objects.filter(Q(email=data)).first()
			if user:
				mail_subject = "Password Reset Requested"
				email_template_name = "users/password/password_reset_email.txt"
				context = {
                "email":user.email,
                'domain':'127.0.0.1:8000',
                'site_name': 'Website',
                "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                "user": user,
                'token': default_token_generator.make_token(user),
                'protocol': 'http',
                }
				message = render_to_string(email_template_name, context)
				try:
					reset_password_mail.send_reset_email_mail.delay(mail_subject, message, user.email)
				except BadHeaderError:
					return HttpResponse('Invalid header found.')
				return redirect ("/users/password-reset/done/")
			return HttpResponse("This mail is not authorized")
	password_reset_form = PasswordResetForm()
	return render(request=request, template_name="users/password/password_reset.html", context={"password_reset_form":password_reset_form})


@login_required(login_url='/users/user-login/')
def wishlist(request):
    return render(request, 'users/wishlist.html')

@login_required(login_url='/users/user-login/')
def checkout(request: HttpRequest) -> HttpResponse:
    
    user = request.user
    checkout_form = CheckoutOrder(initial={'receiver': f'{user.first_name} {user.last_name}'})
    cart = get_user_cart(user.id)
    cart_items = cart.cartitem.all()
    if request.META.get("HTTP_X_REQUESTED_WITH") == "XMLHttpRequest" and request.method == "POST":

        if round(cart.get_cart_total, 2) != float(request.POST['total']):

            return JsonResponse({'status': 0, 'error': 'You must be pay correct amount!'})

        user_id = request.user
        order = Order.objects.create(
            user = user_id,
            phone = request.POST['phone'],
            receiver = request.POST['receiver'],
            total = request.POST['total'],
            products_quantity = request.POST['products_quantity'],
            city = request.POST['city'],
            street = request.POST['street'],
            building = request.POST['building'],
            zip = request.POST['zip'],
            status = 'on_processing',
        )
        order.save()
        cart = Cart.objects.get(owner=user, is_complete=False)

        for item in cart.cartitem.all():
            OrderItem.objects.create(
                order=order,
                quantity=item.quantity,
                product=item.product,
            )
        cart.cartitem.all().delete()
    
    
        return JsonResponse({'status': 1, 'success': '/users/order-success'})
       
           
            
    
    context = {
        'form': checkout_form,
        'user': user,
        'cart': cart,
        'cart_items': cart_items,
    }
    return render(request, 'users/checkout.html', context=context)


@login_required(login_url='/users/user-login/')
def order_success(request: HttpRequest) -> HttpResponse:
    user_id = request.user.id
    order_detail = get_order_details(user_id)
    order_items = order_detail.orderitem_set.all()
   
    context = {
        'order': order_detail,
        'order_items': order_items,
    }

    return render(request, 'users/order_success.html', context=context)


def register(request: HttpRequest) -> HttpResponse:
    register_form = RegisterForm()
    if request.META.get("HTTP_X_REQUESTED_WITH") == "XMLHttpRequest" and request.method == "POST":
        register_form = RegisterForm(request.POST)
        
        if register_form.is_valid():
            print(1)
            user = register_form.save(commit=False)
            print(2)
            user.is_active = False
            user.save()
            # to get the domain of the current site
            current_site = get_current_site(request).domain
            mail_subject = 'Activation link has been sent to your email id'
            info = {"pk": user.pk, "password": register_form.cleaned_data['password1']}
            context = {
                'user': user,  
                'domain': current_site,  
                'uid':urlsafe_base64_encode(force_bytes(info)),  
                'token':account_activation_token.make_token(user),
                'protocol': "https" if request.is_secure() else "http",
            }
            to_email = register_form.cleaned_data['email']
            message = render_to_string('users/acc_active_email.html', context)
            activation_mail.send_activate_email_mail.delay(mail_subject=mail_subject, message=message, to_email=to_email)
            message = f'Please {user.first_name} {user.last_name} confirm your email address to complete the registration. Note: Check your spam folder.'
            data = {
                'success': True,
                'message': message
            }    
            return JsonResponse(data)
        else:
            data = {
                'errors': register_form.errors
            }
            return JsonResponse(data)
    contex ={
        'form' : register_form
    }

    return render(request, 'users/register.html', context=contex)


def activate(request: HttpRequest, uidb64, token) -> HttpResponse:
    try:
        data = force_str(urlsafe_base64_decode(uidb64))
        data = ast.literal_eval(data)
        user = UserModel.objects.get(pk=data['pk'])  
    except:  
        user = None
    
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        create_cart_after_user_registered(user=user)
        new_user = authenticate(username=user.username,
                                password=data['password'])
      
        login(request, new_user)
        return redirect(reverse('core:home'))
    else:
        return HttpResponse('Activation link is invalid!') 


class PasswordsChangeView(PasswordChangeView):

    form_class = PasswordChangeForm
    success_url: Optional[str]
    success_url = reverse_lazy("core:home")


oauth = OAuth()

oauth.register(
    "auth0",
    client_id=settings.AUTH0_CLIENT_ID,
    client_secret=settings.AUTH0_CLIENT_SECRET,
    client_kwargs={
        "scope": "openid profile email",
    },
    server_metadata_url=f"https://{settings.AUTH0_DOMAIN}/.well-known/openid-configuration",
)


def login_user(request: HttpRequest) -> HttpResponse:
    return oauth.auth0.authorize_redirect(
        request, request.build_absolute_uri(reverse("users:auth-callback"))
    )


def auth_callback(request: HttpRequest) -> HttpResponse:
    user: dict = oauth.auth0.authorize_access_token(request)
    if user["userinfo"].get("given_name"):
        created_user = create_user_if_not_exist(
            first_name=user["userinfo"]["given_name"],
            last_name=user["userinfo"]["family_name"],
            email=user["userinfo"]["email"],
        )
    else:
        created_user = create_user_if_not_exist(
            first_name=user["userinfo"]["email"],
            last_name=user["userinfo"]["email"],
            email=user["userinfo"]["email"],
        )

    login(request, created_user)
    create_cart_after_user_registered(user=created_user)
    request.session["user"] = user
    return redirect(request.build_absolute_uri(reverse("core:home")))



@login_required(login_url='/users/user-login/')
def logout(request: HttpRequest) -> HttpResponse:
    request.session.clear()

    return redirect(
        f"https://{settings.AUTH0_DOMAIN}/v2/logout?"
        + urlencode(
            {
                "returnTo": request.build_absolute_uri(reverse("core:home")),
                "client_id": settings.AUTH0_CLIENT_ID,
            },
            quote_via=quote_plus,
        ),
    )

src/users/templates/users/acc_active_email.html
{% autoescape off %}  

    Hi {{ user.username }},  
    Please click on the link to confirm your registration,  
    http://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}  
{% endautoescape %}  

src/users/templates/users/checkout.html
{% extends "core/base.html" %}

{% load static %}
{% load my_tags %}
{% block head %}



<link href="{% static 'css/carousel.css' %}" rel="stylesheet">
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">

<link href="{% static 'css/custom-scroll/jquery.mCustomScrollbar.css' %}" rel="stylesheet">

<style>
  .custom_scroll {
    overflow-y: scroll;
    height: 355px;
  }
</style>

{% endblock %}
{% block content %}


<div class="white">
  <div class="container checkout">
    <h1>Checkout order</h1>
    <hr class="offset-sm">
  </div>
</div>
<hr class="offset-md">

<div class="container checkout">
  <form action="" id="checkout-form" method="post">
    {% csrf_token %}
    <div class="row">
      <div class="col-md-7">
        <div class="row group">
          <div class="col-sm-4">
            <h2 class="h4">{{form.receiver.label}}</h2>
          </div>
          <div class="col-sm-8">
            {{form.receiver}}
          </div>
        </div>

        <div class="row group">
          <div class="col-sm-4">
            <h2 class="h4">{{form.phone.label}}</h2>
          </div>
          <div class="col-sm-8">
            {{form.phone}}
          </div>
        </div>

        <div class="group">
          <div class="row">
            <div class="col-sm-4">
              <h2 class="h4">{{form.city.label}}</h2>
              {{form.city}}
            </div>
            <div class="col-sm-4">
              <h2 class="h4">{{form.street.label}}</h2>
              {{form.street}}
            </div>
            <div class="col-sm-2">
              <h2 class="h4">{{form.building.label}}</h2>
              {{form.building}}
            </div>
            <div class="col-sm-2">
              <h2 class="h4">{{form.zip.label}}</h2>
              {{form.zip}}
            </div>
          </div>
        </div>
        <br>
        <br>
        <p class="error"></p>
        <hr class="offset-lg visible-xs visible-sm">
        <hr class="offset-lg visible-xs">
      </div>

      <div class="col-md-5 white custom_scroll">
        <hr class="offset-md visible-xs visible-sm">
        <div class="checkout-cart">
          <div class="content">
            {% for cart_item in cart_items %}
            <div class="media" data-cart="{{cart.id}}" data-item="{{cart_item.id}}"
              data-product="{{cart_item.product.id}}">
              <div class="media-left">
                <a href="#">
                  <img class="media-object" src="{{ cart_item.product.main_image.url }}"
                    alt="{{ cart_item.product.title }}" />
                </a>
              </div>
              <div class="media-body">
                <h2 class="h4 media-heading">{{ cart_item.product.title | title}}</h2>
                <label>{{ cart_item.product.category | title}}</label>
                {% if cart_item.product.campaign.percent %}
                <p>$ <span class="item-price">{{ cart_item.product.discounted_price | floatformat:2 }}</span></p>
                {% else %}
                <p>$ <span class="item-price">{{ cart_item.product.price }}</span></p>
                {% endif %}
                <p>Total: $ <span class="subtotal-price">{{ cart_item.get_total }}</span></p>
              </div>
              <div class="controls">
                <div class="input-group">
                  <span class="input-group-btn">
                    <button class="btn btn-default btn-sm" type="button" data-action="minus"><i
                        class="ion-minus-round"></i></button>
                  </span>
                  <input type="text" class="form-control input-sm" placeholder="Qty" id="quantity"
                    value="{{cart_item.quantity}}" readonly="">
                  <span class="input-group-btn">
                    <button class="btn btn-default btn-sm" type="button" data-action="plus"><i
                        class="ion-plus-round"></i></button>
                  </span>
                </div><!-- /input-group -->

                <a href="#remove"> <i class="ion-trash-b"></i> Remove </a>
              </div>
            </div>
            {% endfor %}


          </div>
        </div>
        <hr class="offset-md visible-xs visible-sm">
      </div>

      <hr class="offset-lg hidden-xs">

      <div class="col-sm-12 white">
        <hr class="offset-md">
        <div class="row">
          <div class="col-xs-6 col-md-4">
            <h2 class="h4 no-margin total">Total: $ <span>{{cart.get_cart_total | floatformat:2}}</span></h2>
          </div>
          <div class="col-md-4 hidden-xs">
            
          </div>
          <div class="col-xs-6 col-md-4">
            <div id="paypal-button-container"></div>
            <!-- <button class="btn btn-primary pull-right" id="paypal-button-container" type="button">Confirm order</button> -->
          </div>
        </div>
        <hr class="offset-md">
      </div>

    </div>
  </form>
</div>

<hr class="offset-lg">
<hr class="offset-sm">

{%endblock%}


{%block footer%}




<script type="text/javascript" src="{% static 'js/custom-scroll/jquery.mCustomScrollbar.concat.min.js' %}"></script>

<script type="text/javascript" src="{% static 'js/jquery-ui-1.11.4.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.ui.touch-punch.js' %}"></script>


<script 
src="https://www.paypal.com/sdk/js?client-id=Ae0CEVS3yB5MqbNcyADTeZ-wV_OEUKiOZjXKiBVrJE7hQYLRaeNu4yEne1wsT7iBKGqIN0A5_ISwDBZ2&currency=USD&intent=capture&disable-funding=credit,card"
  data-sdk-integration-source="integrationbuilder"></script>
<script src="{% static 'js/checkout.js' %}"></script>


{%endblock%}

src/users/templates/users/login.html
{% extends "core/base.html" %}
{% load static %}

{% block head %}


<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">

<link href="{% static 'css/custom-scroll/jquery.mCustomScrollbar.css' %}" rel="stylesheet">
<link rel="stylesheet" href="http:////netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
<link href="{% static 'css/carousel.css' %}" rel="stylesheet">
<link href="{% static 'css/change-password.css' %}" rel="stylesheet">
<style>
    .fb-color {
        background-color: #3C599F;
    }

    .social-login {
        border-radius: 50%;
        color: #fff;
        box-shadow: 1px 1px 3px #333;
        width: 50px;
        height: 50px;
        line-height: 50px !important;
        text-align: center;
        transition: all 0.3s ease-in-out;
        font-size: 1.8em;
    }

    .google-color {
        background-color: #CF3D2E;
    }
</style>

{%endblock%}

{% block content %}

{% csrf_token %}

<div class="changePassword">
    <div class="container">
        <div class="changePasswordMain">
            <div class="changePasswordTop">
                <h2>Login</h2>
            </div>
            
                <div class="changePasswordBottom" onSubmit={handleSubmit(onSubmit)}>
                    <form action="{% url 'users:user-login' %}" method="POST">
                        {{form.non_field_errors }}
                        {% csrf_token %}
                    <div>
                        <label>Email or Username</label>
                        <input type="text" class="form-control" placeholder="Enter your Email or Username"
                            name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150"
                            required="" id="id_username">
                        {% for error in form.username.errors %}
                        <li class="text-danger">
                            {{error}}
                        </li>
                        {% endfor %}
                    </div>
                    <div>
                        <label>Password</label>
                        <input type="password" name="password" class="form-control" placeholder="Enter your Password"
                            autocomplete="current-password" required="" id="id_password">
                        {% for error in form.password.errors %}
                        <li class="text-danger">
                            {{error}}
                        </li>
                        {% endfor %}
                    </div>

                    <div>

                        <a href="{% url 'users:password_reset' %}" class="forgot-password">Forgot password?</a>
                    </div>
                    <button type="submit">
                        Login
                    </button>

                    <div>
                        <a href="{% url 'users:register' %}">Don't have an account? Sign up</a>
                    </div>
                    <div class="socials_e">
                        <div>
                            <a href="{% url 'users:login' %}" class="social"><i
                                    class="fa fa-facebook social-login fb-color"></i></a>
                            <a href="{% url 'users:login' %}" class="social"><i
                                    class="fa fa-google-plus social-login google-color"></i></a>
                        </div>

                    </div>
                </form>
                    <div class="svg">
                        <img src="{% static 'ionicons-2.0.1/png/icon/password-login.svg' %}" />
                    </div> 
        </div>
    </div>
</div>
{% endblock content %}


{%block footer%}
<script type="text/javascript" src="{% static 'js/carousel.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.touchSwipe.min.js' %}"></script>

<script type="text/javascript" src="{% static 'js/custom-scroll/jquery.mCustomScrollbar.concat.min.js' %}"></script>


<script type="text/javascript" src="{% static 'js/jquery-ui-1.11.4.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.ui.touch-punch.js' %}"></script>
{%endblock%}

src/users/templates/users/order_success.html
{% extends "core/base.html" %}

{% load static %}

{% block head %}
<link href="{% static 'css/order-success.css' %}" rel="stylesheet">
{% endblock head%}
{% block content %}

<div class="order_confirmed">
    <div class="order_container">
        <div class="order_info_1">
            <div class="order_image_part">
                <h2>Your Order Confirmed!</h2>
                <img src="https://png.pngtree.com/png-vector/20190228/ourmid/pngtree-check-mark-icon-design-template-vector-isolated-png-image_711429.jpg"
                    alt="order_success_image"></div>
            
            <p>Hi {{ request.user.first_name }}, Your order has been confirmed and will be shipping soon.</p>
        </div>
        <ul class="order_info_2">
            <li>
                <p>Order Date</p>
                <span>{{ order.created_at }}</span>
            </li>
            <li>
                <p>Order Number</p>
                <span>#{{ order.id }}</span>
            </li>
           
            <li>
                <p>Address</p>
                <span>{{ order.city }}, {{ order.street }}</span>
            </li>
        </ul>
        
        <div class="order_products">
            {% for item in order_items %}   
                <div class="order_product">
                    <img src="{{ item.product.main_image.url }}"
                    alt="{{ item.product }}">
                    <div class="product_name">
                        <p>{{ item.product | title }}</p>
                        <span>{{ item.product.category | title }}</span>
                    </div>
                    <p>Qty {{ item.quantity }}</p>
                    <p class="order_total">${{item.get_total}}</p>
                    
                </div>
            {% endfor %}
        
            
        </div>
        <div class="order_total">
            <div>
                <p>Payment Total</p>
                <span>$ {{ order.total }}</span>
            </div>
            <div>
                <p>Payment Method</p>
                <span>{{ order.payment | title }}</span>
            </div>
        </div>
        <div class="order_last">
            <p>We'll send you shipping confirmation when your item(s) are on the way! We appreciate your bisiness,
                and hope you enjoy your purchase.</p>
            <span>Thanks for choosing us!</span>
        </div>
    </div>
</div>

{% endblock content %}
{% block footer %}

{% endblock footer %}

src/users/templates/users/register.html
{% extends "core/base.html" %}
{% load static %}

{% block head %}

<link href="{% static 'css/carousel.css' %}" rel="stylesheet">
<link href="{% static 'css/change-password.css' %}" rel="stylesheet">
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">

<link href="{% static 'css/custom-scroll/jquery.mCustomScrollbar.css' %}" rel="stylesheet">

{%endblock%}

{% block content %}
<div class="changePassword">
    <div class="container">
        <div class="changePasswordMain">
            <div class="changePasswordTop">
                <p id="register-message"></p>
                <h2>Register</h2>
            </div>
            
                <div class="changePasswordBottom">
                    <form method="POST" id="registerForm" action="{% url 'users:register' %}">
                        {% csrf_token %}
                    <div>
                        {{form.first_name}}
                    </div>
                    <div>
                        {{form.last_name}}
                    </div>
                    <div>
                        {{form.username}}
                       <ul style="margin: auto 0; max-width: 400px;"></ul>
                    </div>
                    <div>
                        {{form.email}}
                       <ul style="margin: auto 0; max-width: 400px;"></ul>
                    </div>
                    <div>
                        {{form.password1}}
                       <ul style="margin: auto 0; max-width: 400px;"></ul>
                    </div>
                    <div>
                        {{form.password2}}
                       <ul style="margin: auto 0; max-width: 400px;"></ul>
                    </div>
                    <button type="submit">
                        Sign Up
                    </button>
                    <div>
                        <a href="{% url 'users:user-login' %}" class="">Have already an account? Login here</a>
                    </div>
                    
                </form>
                <div class="svg">
                    <img style="width: 350px; height: 350px" src="{% static 'ionicons-2.0.1/png/icon/password-login.svg' %}" />
                </div> 
                </div>
            

        </div>
        {% comment %} <div class="svg">
            <img src="{% static 'img/password/password.png' %}" />
        </div> {% endcomment %}
    </div>
</div>
{% endblock content %}


{%block footer%}
<script type="text/javascript" src="{% static 'js/carousel.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.touchSwipe.min.js' %}"></script>

<script type="text/javascript" src="{% static 'js/custom-scroll/jquery.mCustomScrollbar.concat.min.js' %}"></script>


<script type="text/javascript" src="{% static 'js/jquery-ui-1.11.4.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.ui.touch-punch.js' %}"></script>
<script type="text/javascript" src="{% static 'js/register.js' %}"></script>

{%endblock%}