src/api/urls.py
from django.urls import path
from api.views import *
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

app_name = "api"

urlpatterns = [
    path('register/', RegisterApiView.as_view(), name='users_register'),
    path('token/', TokenObtainPairView.as_view(), name='token-obtain-pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token-refresh'),
    path('category/', CategoryListCreateAPIView.as_view(), name='category-list'),
    path('category/<int:pk>/', CategoryRetrieveUpdateAPIView.as_view(), name='category-retrieve-update-destroy'),

    path('product/', ProductListCreateView.as_view(), name='product_list'),
    path('product/<int:pk>/', ProductRetrieveUpdateAPIView.as_view(), name='product_retrieve_update_destroy'),
    path("blog/", BlogListCreateView.as_view(), name='blog_list'),
    path("blog/<int:pk>/", BlogRetrieveUpdateAPIView.as_view(), name='blog_retrieve_update_destroy'),
    path('media/<int:pk>/', MediaRetrieveUpdateAPIView.as_view(), name='media_retrieve_update_destroy'),
    path('display/<int:pk>/', DisplayRetrieveUpdateAPIView.as_view(), name='display_retrieve_update_destroy'),
    path('wireless/<int:pk>/', WirelessRetrieveUpdateAPIView.as_view(), name='wireless_retrieve_update_destroy'),
    path('campaign/<int:pk>/', CampaignRetrieveUpdateAPIView.as_view(), name='campaign_retrieve_update_destroy'),
    path('brand/<int:pk>/', BrandRetrieveUpdateAPIView.as_view(), name='brand_retrieve_update_destroy'),
    path('screen/<int:pk>/', ScreenRetrieveUpdateAPIView.as_view(), name='screen_retrieve_update_destroy'),
    path('cart/', CartListCreateAPIView.as_view(), name='cart_list_create'),
    path('cart/<int:pk>', CartRetrieveUpdateAPIView.as_view(), name='cart_retrieve_update_destroy'),
    path('cart-item/', CartItemListCreateAPIView.as_view(), name='cart_item_list_create'),
    path('cart-item/<int:pk>', CartItemRetrieveUpdateAPIView.as_view(), name='cart_retrieve_update_destroy'),
    path('order/', OrderListCreateAPIView.as_view(), name='order_list_create'),
    path('order/<int:pk>', OrderRetrieveUpdateAPIView.as_view(), name='order_retrieve_update_destroy'),
    path('order-item/', OrderItemListCreateAPIView.as_view(), name='order_item_list_create'),
    path('order-item/<int:pk>', OrderItemRetrieveUpdateAPIView.as_view(), name='order_retrieve_update_destroy'),
    path('wishlist/', WishlistListCreateAPIView.as_view(), name='wishlist_list_create'),
    path('wishlist/<int:pk>', WishlistRetrieveUpdateDestroyAPIView.as_view(), name='wishlist_retrieve_update_destroy'),
]

src/blog/urls.py
from django.urls import path
from . import views

from blog.views import BlogListView

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='blog'),
    path('<slug:slug>/', views.detail_blog, name='blog-detail')
]

src/core/urls.py
from django.urls import path, include
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name="contact"),
    path('about-contact/', views.about_contact, name="about"),
    path('faq/', views.faq, name="faq"),
    path('subscribe/', views.subscribe, name="subscribe"),
]

src/product/urls.py
from django.urls import path, re_path
from product.views import  ProductListView, ProductDetailView

app_name = 'product'


urlpatterns = [
    path('', ProductListView.as_view(), name='product-list'),

    path('<slug:slug>/', ProductDetailView.as_view(), name='product-detail'),
   
]

src/unistore/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

from core.views import search

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('blog/', include('blog.urls')),
    path('products/', include('product.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
   
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
  
    path('search/', search, name='search'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]
urlpatterns = [
    *i18n_patterns(*urlpatterns, prefix_default_language=False),
]

src/core/models.py
from django.db import models
from django.core.validators import validate_email

# Create your models here.
class Subscriber(models.Model):
    email = models.EmailField(max_length=100)
    added_at = models.DateTimeField(auto_now_add=True)
    def __str__(self) -> str:
        return self.email

class Contact(models.Model):
    mail = models.EmailField(
        max_length=128,
        blank=False,
        unique=False,
        validators=[validate_email],
        error_messages={
            'required': 'Please provide your email address.',
            'unique': 'An account with this email exist.'
        }
        ) #REMIND
    message = models.TextField()

    def __str__(self) -> str:
        return self.mail

src/core/forms.py
from django import forms
from core.models import Contact, Subscriber

class ContactForm(forms.ModelForm):
     class Meta:
        model = Contact
        fields = "__all__"
        widgets = {
            "message": forms.Textarea(attrs={
                'class': 'form-control',
                'name': 'message',
                'placeholder': 'Message',
                'rows': 5
                }),
            "mail": forms.EmailInput(attrs={
                'class': 'form-control',
                'name': 'email',
                'placeholder': 'E-mail',
                'required': True                
                }),
        }


class SubscribeToNewsletter(forms.ModelForm):
    class Meta:
        model = Subscriber
        fields = ("email",)
        widgets = {
            "email": forms.EmailInput(attrs={
                'class': 'form-control',
                'data-name': 'subscribe',
                'type': 'email',
                'name': 'email',
                'placeholder': 'E-mail',
                })
            }
  

src/core/views.py
import json

from django.shortcuts import render
from django.core.cache.backends.base import DEFAULT_TIMEOUT
from django.http.request import HttpRequest
from django.conf import settings
from django.views.decorators.cache import cache_page
from django.http.response import HttpResponse
from django.http import JsonResponse

from core.models import Subscriber
from core.forms import SubscribeToNewsletter, ContactForm
from product.services.products import get_products, get_popular_products, search_product, product_list, get_campaigns
from blog.services.blog import last_six_blogs, searched_blog
from tasks.tasks.contact_mail import send_contact_email

CACHE_TTL = getattr(settings, 'CACHE_TTL', DEFAULT_TIMEOUT)

def home(request: HttpRequest) -> HttpResponse:
    categories = get_products().values('category', 'category__name').distinct()[:3]
    object_list = product_list()
    blogs = last_six_blogs()[:2]
    popular_prods = get_popular_products()[:3]
    first_campaign = get_campaigns().filter(id=5).first()
    third_campaign = get_campaigns().filter(id=4).first()
    subscriber_form = SubscribeToNewsletter()
 

    context={
            "subscriber_form": subscriber_form, 
            "session": request.session.get("user"), 
            "pretty": json.dumps(request.session.get("user"), indent=4),
            "categories": categories,
            "product_list": object_list,
            "blogs": blogs,
            "popular_prods": popular_prods,
            "first_campaign": first_campaign,
            "third_campaign": third_campaign
            }
    return render(
        request=request, 
        template_name='core/index.html', 
        context=context,
        )

def contact(request: HttpRequest) -> HttpResponse:

    form = ContactForm()
    if "contact" in request.POST:
        print(request.POST)
        if request.method == "POST":
            form = ContactForm(request.POST)
            
            if form.is_valid():
                send_contact_email(
                    email=form.cleaned_data["mail"],
                    message=form.cleaned_data["mail"],
                )
                form.save()
                form.cleaned_data["mail"]
                form.cleaned_data["mail"]

    context = {
        "form": form
    }

    return render(request, 'core/contact.html', context=context)


@cache_page(CACHE_TTL)
def about_contact(request: HttpRequest) -> HttpResponse:
    return render(request, 'core/about_contact.html')

@cache_page(CACHE_TTL)
def faq(request: HttpRequest) -> HttpResponse:
    return render(request, 'core/faq.html')


def subscribe(request: HttpRequest):
    
    subscriber_form = SubscribeToNewsletter()
    if "email" in request.POST:
        print(request.POST)
        if request.META.get("HTTP_X_REQUESTED_WITH") == "XMLHttpRequest" and request.method == "POST":
            subscriber_form = SubscribeToNewsletter(request.POST)
        
            if subscriber_form.is_valid():
                Subscriber.objects.get_or_create(
                    email = subscriber_form.cleaned_data["email"]
                    )
                message = "Congratulation!! You subscribed successfully"
                return JsonResponse({'message': message})
            


def search(request: HttpRequest) -> HttpResponse:
    query = request.GET.get("query")
    if query: 
        results= search_product(data=query) 
    return render(request, "core/search.html", {"results": results})

src/core/templates/core/about_contact.html
{% extends "core/base.html" %}

{% load static %}

{% block head %}

    <!-- Bootstrap -->
    <link href="{% static 'css/carousel.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <link href='https://fonts.googleapis.com/css?family=Catamaran:400,100,300' rel='stylesheet' type='text/css'>

    <link href="{% static 'css/custom-scroll/jquery.mCustomScrollbar.css' %}" rel="stylesheet">
{% endblock head %}

    <!-- block content start -->
   
    {% block content %}
     <header>
      <div class="carousel" data-count="1" data-current="1">
        <div class="items">
          <div class="item center" data-marker="1">
            <img src="{% static 'img/carousel/bckg-3.jpg' %}" alt="Background" class="background hidden-xs hidden-sm"/>
            <img src="{% static 'img/carousel/bckg-3-sm.jpg' %}" alt="Background" class="background visible-sm"/>
            <img src="{% static 'img/carousel/bckg-3-xs.jpg' %}" alt="Background" class="background visible-xs"/>

            <div class="content">
              <div class="outside-content">
                <div class="inside-content">
                  <div class="container align-right">
                    <hr class="offset-lg visible-xs">

                    <h1 class="h3 upp colorful blue">Beautiful, smart and powerful</h1>
                    <hr class="offset-sm">

                    <h2 class="h1 lg upp colorful blue">Brand new <br> devices for all</h2>
                    <hr class="offset-md">
                    <hr class="offset-md">
                    <a href="{% url 'product:product-list' %}" rel="nofollow" class="btn btn-primary btn-lg black"> Buy now </a>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </header> 
    
     <div class="white">
      <hr class="offset-lg">
      <hr class="offset-lg">
      <hr class="offset-lg">
      <hr class="offset-lg hidden-xs hidden-sm">

      <div class="container about">
        <div class="row">
          <div class="col-sm-6 hidden-sm hidden-md hidden-lg">
            <img src="{% static 'img/about/anytime-mobility.png' %}" alt="Anywhere, anytime mobility" title="Anywhere, anytime mobility"/>
          </div>
          <div class="col-sm-6">
            <hr class="offset-lg hidden-xs hidden-sm">
            <hr class="offset-lg hidden-xs hidden-sm">
            <h2 class="featurette-heading">Anywhere, anytime mobility.</h2>
            <hr class="offset-md">

            <p class="lead">
              School, home, or on the road, the slim design, and latest processors give you everything you need to take on the world.
              Conveniently store up to 100GB of your files and content with the included 2-years of Google Drive access.
              With up to 9.5 hours of long lasting battery, search, stream, chat, and more for hours without recharging.
            </p>
          </div>
          <div class="col-sm-6 hidden-xs">
            <hr class="offset-lg visible-sm">
            <hr class="offset-lg visible-sm">
            <img src="{% static 'img/about/anytime-mobility.png' %}" alt="Anywhere, anytime mobility" title="Anywhere, anytime mobility"/>
          </div>
        </div>
      </div>

      <hr class="offset-lg">
      <hr class="offset-lg">
      <hr class="offset-lg hidden-xs">
    </div> 
    <hr class="offset-lg">
    <hr class="offset-lg">

    <div class="">
      <hr class="offset-lg hidden-xs">
      <hr class="offset-lg hidden-xs">
      <div class="container about">
        <div class="row">
          <div class="col-sm-6">
            <hr class="offset-lg visible-sm">
            <img src="{% static 'img/about/new-entertainment.png' %}" alt="Anywhere, anytime mobility" title="Anywhere, anytime mobility"/>
          </div>
          <div class="col-sm-6">
            <hr class="offset-lg hidden-xs hidden-sm">
            <hr class="offset-lg hidden-xs hidden-sm">
            <h2 class="featurette-heading">Entertainment at your fingertips.</h2>
            <hr class="offset-md">

            <p class="lead">
              Capture all the details with vibrant clarity, even in low light. Enjoy the nuances of face-to-face conversations, 
              thanks to the HD Webcam. Lay back and get comfortable with your favorite movies and shows. 
              The HD IPS screens delivers your entertainment in stunning quality, from any angle.
            </p>
          </div>
        </div>
      </div>
      <hr class="offset-lg">
      <hr class="offset-lg">
    </div>



    <hr class="offset-lg hidden-xs">
    <hr class="offset-lg hidden-xs">
    <hr class="offset-lg hidden-xs">
    <div class="white">
      <hr class="offset-lg hidden-xs">
      <hr class="offset-lg hidden-xs">
      <hr class="offset-lg">

      <div class="container about">
        <div class="row">
          <div class="col-sm-6 hidden-sm hidden-md hidden-lg">
            <img src="{% static 'img/about/sleek-and-colorful.png' %}" alt="Sleek and colorful" title="Sleek and colorful"/>
          </div>
          <div class="col-sm-6">
            <hr class="offset-lg hidden-xs hidden-sm">
            <hr class="offset-lg hidden-xs hidden-sm">
            <h2 class="featurette-heading">Sleek and powerfull.</h2>
            <hr class="offset-md">

            <p class="lead">
              With the brand new laptops running lightning-fast Windows 10, the best of Microsoft is at hand on a colorfully 
              sleek and stylish notebook. Express yourself with an HD 29.5 cm (11.6") diagonal screen in a slim package, 
              styled in smoke silver or sky blue.
            </p>
          </div>
          <div class="col-sm-6 hidden-xs">
            <hr class="offset-lg visible-sm">
            <img src="{% static 'img/about/sleek-and-colorful.png' %}" alt="Sleek and colorful" title="Sleek and colorful"/>
          </div>
        </div>
      </div>

      <hr class="offset-lg">
      <hr class="offset-lg hidden-xs">
      <hr class="offset-lg hidden-xs">
    </div>
    

    {% endblock content%}
    {% block footer %}
   
    
    <script type="text/javascript" src="{% static 'js/custom-scroll/jquery.mCustomScrollbar.concat.min.js' %}"></script>

    <script type="text/javascript" src="{% static 'js/jquery-ui-1.11.4.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.ui.touch-punch.js' %}"></script>
    
  {% endblock footer %}

src/core/templates/core/index.html
{% extends "core/base.html" %}
{% load static %}
{% load i18n %}
{% load my_tags %}
{% block head %}




    <!-- Bootstrap -->
   
    <link href="{% static 'css/carousel.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
   
    <link href="{% static 'css/custom-scroll/jquery.mCustomScrollbar.css' %}" rel="stylesheet">
    
    <style>
      .body{
        display: flex;
        flex-direction: column;
        align-items: center;
      }
      .image-height{
        height: 250px;

      }
      .image-height img{
        height: 100% !important;
      }
      .detailsButton{
        text-align: center !important;
      }
      .fontSize{
        font-size: 18px;
      }
    </style>

{%endblock%}
{%block content%}
  

    <header>
      <div class="carousel" data-count="2" data-current="1">

        <div class="items">
          <button class="btn btn-control" data-direction="right"> <i class="ion-ios-arrow-right"></i></button>
          <button class="btn btn-control" data-direction="left"> <i class="ion-ios-arrow-left"></i></button>
          
          
          <div class="item center" data-marker="1">
            <img src="{{ first_campaign.image.url }}" alt="Background" class="background hidden-xs hidden-sm"/>
            <img src="{{ first_campaign.image.url }}" alt="Background" class="background visible-sm"/>
            <img src="{{ first_campaign.image.url }}" alt="Background" class="background visible-xs"/>

            <div class="content">
              <div class="outside-content">
                <div class="inside-content">
                  <div class="container">

                     <h1 class="h2 colorful blue hidden-xs">{{ first_campaign.description }}</h1>  

                    <hr class="offset-sm">
                    <h2 class="h1 lg upp colorful blue">{{ first_campaign| title }}</h2>
                    <hr class="offset-md">
                    <hr class="offset-md">
                    <a href="/products/?campaign={{ first_campaign.id }}" data-value="{{ first_campaign.id }}" rel="nofollow" class="btn btn-primary btn-lg black campaign"> {% trans "More"%} </a>

                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="item" data-marker="2">
            <img src="{{ third_campaign.image.url }}" alt="Background" class="background hidden-xs hidden-sm"/>
            <img src="{{ third_campaign.image.url }}" alt="Background" class="background visible-sm"/>
            <img src="{{ third_campaign.image.url }}" alt="Background" class="background visible-xs"/>

            <!-- <img src="assets/img/carousel/ipadair2.jpg" alt="Apple Devices" title="Apple Devices" class="item-right hidden-xs"/> -->

            <div class="content">
              <div class="outside-content">
                <div class="inside-content">
                  <div class="container align-right">
                  
                    <h1 class="h3 colorful blue hidden-xs">{{ third_campaign.description }} <br> </h1>

                    <hr class="offset-sm">
                    <h2 class="h1 lg upp colorful blue">{{ third_campaign | title }} <br class="hidden-xs"></h2>
                    <hr class="offset-md">
                    <hr class="offset-md">
                    <a href="/products/?campaign={{ third_campaign.id }}" rel="nofollow" class="btn btn-primary btn-lg black"> {% trans "View products" %} </a>
                      
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <ul class="markers">
          <li data-marker="1" data-style="white" class="active"></li>
          <li data-marker="2" data-style="white"></li>
        </ul>

      </div>
    </header>
    <hr class="offset-lg">
    <hr class="offset-lg">

    <div class="bars">
      <div class="container">
        <div class="row">
          {% for obj in popular_prods %}
          <div class="col-sm-6 col-md-4 padding padding-xs">
            <div class="bar medium" data-background="{{ obj.main_image.url}}">
              <h3 class="title black">{{ obj | title }}</h3>

              <div class="wrapper">
                <div class="content">
                  <hr class="offset-sm">
                  <a href="{% url 'product:product-detail' slug=obj.slug %}" rel="nofollow" class="btn btn-default black"> {% trans "Buy now" %} </a>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}

          {% comment %} <div class="col-sm-6 col-md-4 no-padding padding-xs">
            <div class="bar medium" data-background="{{ popular_prods.0 }}">
              <h3 class="title black">{{ popular_prods.0.product | title }}</h3>

              <div class="wrapper">
                <div class="content">
                  <hr class="offset-sm">
                  <a href="{% url 'product:product-detail' slug=popular_prods.0.product.slug %}" rel="nofollow" class="btn btn-default black"> {% trans "Buy now" %} </a>
                </div>
              </div>
            </div>
          </div>
          <div class="col-sm-6 col-md-4 no-padding hidden-xs hidden-sm">
            <div class="bar medium" data-background="{{ popular_prods.3 }}">
              <h3 class="title black">{{ popular_prods.3.product | title }}</h3>
              
              <div class="wrapper">
                <div class="content">
                  <hr class="offset-sm">
                  <a href="{% url 'product:product-detail' slug=popular_prods.3.product.slug %}" rel="nofollow" class="btn btn-primary black"> {% trans "Buy now" %} </a>
                </div>
              </div>
            </div>
          </div> {% endcomment %}
        </div>
      </div>
    </div>
    <hr class="offset-lg">
    <hr class="offset-md">


    <section id="productsGrid">
      {% for category in categories %}
        <section class="products">
          <div class="container">
            <h2 class="h2 upp align-center"> {{ category.category__name }} </h2>
            <hr class="offset-lg">

            <div class="row">
              {% for obj in product_list %}
                {% if obj.category.id == category.category %}
                  <div class="col-sm-6 col-md-3 product">
                    <div class="body">

                          <a href="#favorites" class="favorites" data-favorite="inactive">
                            <!-- <img class="heart-fav" src="{% static 'ionicons-2.0.1/png/icon/empty-heart.png' %}" alt=""> -->
                          </a>

                      <a href="{% url 'product:product-detail' slug=obj.slug %}" class="image-height"><img src="{{ obj.main_image.url }}" alt="{{ obj.title }}"/></a>

                      <div class="content align-center">
                        
                        <h2 class="h3 productName">{{ obj.title | title }}</h2>
                        {% if obj.campaign.percent %}
                        <p class="price ">${{ obj.discounted_price | floatformat:2 }}</p> 
                        <p class="price through">${{ obj.price }}</p>
                        {% else %}
                        <p class="price">${{ obj.price }}</p>
                        {% endif %}
                        <hr class="offset-sm">

                        <button class="btn btn-link detailsButton"> <a class="fontSize" href="{% url 'product:product-detail' slug=obj.slug %}"> <i class="ion-android-open"></i> {% trans "Details" %} </a> </button>
                        {% comment %} <button class="btn btn-primary btn-sm rounded addToCart"> <i class="ion-bag"></i> {% trans "Add to cart" %}</button> {% endcomment %}
                      </div>
                    </div>
                  </div>
                
                  {% endif %} 
              {% endfor %}

            </div>

            <div class="align-right align-center-xs">
              <hr class="offset-sm">
              <a href="/products/?category={{ category.category }}"> <h5 class="upp">{% trans "View all " %}{{category.category__name}} </h5> </a>
            </div>
          </div>
        </section>
      {% endfor %}
    </section>

    
    {% comment %} <section id="productsGrid">
      {% for category in categories %}
        <section class="products">
          <div class="container">
            <h2 class="h2 upp align-center"> {{ category.category__name }} </h2>
            <hr class="offset-lg">

            <div class="row">
              {% for obj in product_list %}
                {% if obj.category.id == category.category %}
                  <div class="col-sm-6 col-md-3 product">
                    <div class="body">

                          <a href="#favorites" class="favorites" data-favorite="inactive"><i class="ion-ios-heart-outline"></i></a>

                    <div class="content align-center">
                      {% if obj.campaign.percent %}
                      <p class="price ">${{ obj.price|discount:obj.campaign.percent }}</p> 
                      <p class="price through">${{ obj.price }}</p>
                      {% else %}
                      <p class="price">${{ obj.price }}</p>
                      {% endif %}
                      <!-- <p class="price">${{ obj.price }}</p> -->
                      <h2 class="h3 productName">{{ obj.title | title }}</h2>
                      <hr class="offset-sm">

                      <div class="content align-center">
                        <p class="price">${{ obj.price }}</p>
                        <h2 class="h3 productName">{{ obj.title | title }}</h2>
                        <hr class="offset-sm">

                        <button class="btn btn-link detailsButton"> <a class="fontSize" href="{% url 'product:product-detail' slug=obj.slug %}"> <i class="ion-android-open"></i> {% trans "Details" %} </a> </button>
                        {% comment %} <button class="btn btn-primary btn-sm rounded addToCart"> <i class="ion-bag"></i> {% trans "Add to cart" %}</button> {% endcomment %}
                      {% comment %} </div>
                    </div>
                  </div>
                
                  {% endif %} 
              {% endfor %}

            </div>

            <div class="align-right align-center-xs">
              <hr class="offset-sm">
              <a href="/products/?category={{ category.category }}"> <h5 class="upp">{% trans "View all " %}{{category.category__name}} </h5> </a>
            </div>
          </div>
        </section>
      {% endfor %}
    </section> {% endcomment %} 


    <section class="blog">
      <div class="container">
        <h2 class="h2 upp align-center"> {% trans "Blog Headlines" %} </h2>
        <hr class="offset-lg">

        <div class="row">
          {% for blog in blogs %}
          <div class="col-sm-6 col-md-6 item">

            <div class="body">
              <a href="{% url 'blog:blog-detail' slug=blog.slug %}" class="view"><i class="ion-ios-book-outline"></i></a>
              <a href="{% url 'blog:blog-detail' slug=blog.slug %}">
                <img src="{{ blog.main_image.url }}" title="{{ blog }}" alt="{{ blog }}">
              </a>

              <div class="caption">
                <h2 class="h3">{{ blog| title }}</h2>
                <label> {{ blog.created_at }}</label>
                <hr class="offset-sm">

                <p>
                  {{ blog.description | truncatewords:40 }}
                </p>
                <hr class="offset-sm">

                <a href="{% url 'blog:blog-detail' slug=blog.slug %}"> {% trans "View article" %} </a>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>

        <div class="align-right align-center-xs">
          <hr class="offset-sm">
          <a href="{% url 'blog:blog' %}"> <h5 class="upp">{% trans "View all articels" %} </h5> </a>
        </div>
      </div>
    </section>


    <hr class="offset-lg">
    <hr class="offset-sm">
   {%endblock%}
 {%block footer%}
    <script type="text/javascript" src="{% static 'js/carousel.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.touchSwipe.min.js' %}"></script>

    <script type="text/javascript" src="{% static 'js/custom-scroll/jquery.mCustomScrollbar.concat.min.js' %}"></script>


    <script type="text/javascript" src="{% static 'js/jquery-ui-1.11.4.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.ui.touch-punch.js' %}"></script>

    <script type="text/javascript" src="{% static 'js/wishlist.js' %}"></script>

{% endblock footer %}

src/core/templates/core/subscriber.html
{% load i18n %}
{% load social_share %}

<div class="subscribe">
    <div class="container align-center">
      <hr class="offset-md">

      <h1 class="h3 upp">{% trans "Join our newsletter" %}</h1>
      <p>{% trans "Get more information and receive special discounts for our products." %}</p>
      <hr class="offset-sm">

      <form action="{% url 'core:subscribe' %}" id="subscribe" method="post">
        {% csrf_token %}
        <div class="input-group">
          {{subscriber_form.email}}
          <span class="input-group-btn">
            <button name="subscribe" type="submit" class="btn btn-primary"> Subscribe <i class="ion-android-send"></i>
            </button>
          </span>
          
        </div><!-- /input-group -->
          {% comment %} {%for error in subscriber_form.email.errors%}
            <li class="text-danger">{{error}}</li>
          {%endfor%} {% endcomment %}
          <p id="message" style="margin-top: 10px; padding: 5px; color: green; font-size: 18px;"></p>
      </form>
      <hr class="offset-lg">
      <hr class="offset-md">

      <div class="social">
        <a href="#"><i class="ion-social-facebook"></i></a>
        <a href="#"><i class="ion-social-twitter"></i></a>
        <a href="#"><i class="ion-social-googleplus-outline"></i></a>
        <a href="#"><i class="ion-social-instagram-outline"></i></a>
        <a href="#"><i class="ion-social-linkedin-outline"></i></a>
        <a href="#"><i class="ion-social-youtube-outline"></i></a>
      </div>


      <hr class="offset-md">
      <hr class="offset-md">
    </div>
  </div>